
<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml" lang="ja">
  <head>
    <meta charset="utf-8" />
    <title>layout: article title: Handling Errors &#8212; Go database/sql tutorial  ドキュメント</title>
    <link rel="stylesheet" href="_static/alabaster.css" type="text/css" />
    <link rel="stylesheet" href="_static/pygments.css" type="text/css" />
    <script type="text/javascript" id="documentation_options" data-url_root="./" src="_static/documentation_options.js"></script>
    <script type="text/javascript" src="_static/jquery.js"></script>
    <script type="text/javascript" src="_static/underscore.js"></script>
    <script type="text/javascript" src="_static/doctools.js"></script>
    <script type="text/javascript" src="_static/language_data.js"></script>
    <script type="text/javascript" src="_static/translations.js"></script>
    <link rel="index" title="索引" href="genindex.html" />
    <link rel="search" title="検索" href="search.html" />
   
  <link rel="stylesheet" href="_static/custom.css" type="text/css" />
  
  
  <meta name="viewport" content="width=device-width, initial-scale=0.9, maximum-scale=0.9" />

  </head><body>
  

    <div class="document">
      <div class="documentwrapper">
        <div class="bodywrapper">
          

          <div class="body" role="main">
            
  <hr class="docutils" />
<div class="section" id="layout-article-title-handling-errors">
<h1>layout: article
title: Handling Errors<a class="headerlink" href="#layout-article-title-handling-errors" title="このヘッドラインへのパーマリンク">¶</a></h1>
<p>Almost all operations with <code class="docutils literal notranslate"><span class="pre">database/sql</span></code> types return an error as the last
value. You should always check these errors, never ignore them.</p>
<p>There are a few places where error behavior is special-case, or there's
something additional you might need to know.</p>
</div>
<div class="section" id="errors-from-iterating-resultsets">
<h1>Errors From Iterating Resultsets<a class="headerlink" href="#errors-from-iterating-resultsets" title="このヘッドラインへのパーマリンク">¶</a></h1>
<p>Consider the following code:</p>
<pre class="prettyprint lang-go">
for rows.Next() {
	// ...
}
if err = rows.Err(); err != nil {
	// handle the error here
}
</pre><p>The error from <code class="docutils literal notranslate"><span class="pre">rows.Err()</span></code> could be the result of a variety of errors in the
<code class="docutils literal notranslate"><span class="pre">rows.Next()</span></code> loop. The loop
might exit for some reason other than finishing the loop normally, so you always
need to check whether the loop terminated normally or not. An abnormal
termination automatically calls <code class="docutils literal notranslate"><span class="pre">rows.Close()</span></code>, although it's harmless to call it
multiple times.</p>
</div>
<div class="section" id="errors-from-closing-resultsets">
<h1>Errors From Closing Resultsets<a class="headerlink" href="#errors-from-closing-resultsets" title="このヘッドラインへのパーマリンク">¶</a></h1>
<p>You should always explicitly close a <code class="docutils literal notranslate"><span class="pre">sql.Rows</span></code> if you exit the loop
prematurely, as previously mentioned. It's auto-closed if the loop exits
normally or through an error, but you might mistakenly do this:</p>
<pre class="prettyprint lang-go">
for rows.Next() {
	// ...
	break; // whoops, rows is not closed! memory leak...
}
// do the usual "if err = rows.Err()" [omitted here]...
// it's always safe to [re?]close here:
if err = rows.Close(); err != nil {
	// but what should we do if there's an error?
	log.Println(err)
}
</pre><p>The error returned by <code class="docutils literal notranslate"><span class="pre">rows.Close()</span></code> is the only exception to the general rule
that it's best to capture and check for errors in all database operations. If
<code class="docutils literal notranslate"><span class="pre">rows.Close()</span></code> returns an error, it's unclear what you should do.
Logging the error message or panicing might be the only sensible thing,
and if that's not sensible, then perhaps you should just ignore the error.</p>
</div>
<div class="section" id="errors-from-queryrow">
<h1>Errors From QueryRow()<a class="headerlink" href="#errors-from-queryrow" title="このヘッドラインへのパーマリンク">¶</a></h1>
<p>Consider the following code to fetch a single row:</p>
<pre class="prettyprint lang-go">
var name string
err = db.QueryRow("select name from users where id = ?", 1).Scan(&amp;name)
if err != nil {
	log.Fatal(err)
}
fmt.Println(name)
</pre><p>What if there was no user with <code class="docutils literal notranslate"><span class="pre">id</span> <span class="pre">=</span> <span class="pre">1</span></code>? Then there would be no row in the
result, and <code class="docutils literal notranslate"><span class="pre">.Scan()</span></code> would not scan a value into <code class="docutils literal notranslate"><span class="pre">name</span></code>. What happens then?</p>
<p>Go defines a special error constant, called <code class="docutils literal notranslate"><span class="pre">sql.ErrNoRows</span></code>, which is returned
from <code class="docutils literal notranslate"><span class="pre">QueryRow()</span></code> when the result is empty. This needs to be handled as a
special case in most circumstances. An empty result is often not considered an
error by application code, and if you don't check whether an error is this
special constant, you'll cause application-code errors you didn't expect.</p>
<p>Errors from the query are deferred until <code class="docutils literal notranslate"><span class="pre">Scan()</span></code> is called, and then are
returned from that. The above code is better written like this instead:</p>
<pre class="prettyprint lang-go">
var name string
err = db.QueryRow("select name from users where id = ?", 1).Scan(&amp;name)
if err != nil {
	if err == sql.ErrNoRows {
		// there were no rows, but otherwise no error occurred
	} else {
		log.Fatal(err)
	}
}
fmt.Println(name)
</pre><p>One might ask why an empty result set is considered an error. There's nothing
erroneous about an empty set. The reason is that the <code class="docutils literal notranslate"><span class="pre">QueryRow()</span></code> method needs
to use this special-case in order to let the caller distinguish whether
<code class="docutils literal notranslate"><span class="pre">QueryRow()</span></code> in fact found a row; without it, <code class="docutils literal notranslate"><span class="pre">Scan()</span></code> wouldn't do anything and
you might not realize that your variable didn't get any value from the database
after all.</p>
<p>You should only run into this error when you're using <code class="docutils literal notranslate"><span class="pre">QueryRow()</span></code>. If you
encounter this error elsewhere, you're doing something wrong.</p>
</div>
<div class="section" id="identifying-specific-database-errors">
<h1>Identifying Specific Database Errors<a class="headerlink" href="#identifying-specific-database-errors" title="このヘッドラインへのパーマリンク">¶</a></h1>
<p>It can be tempting to write code like the following:</p>
<pre class="prettyprint lang-go">
rows, err := db.Query("SELECT someval FROM sometable")
// err contains:
// ERROR 1045 (28000): Access denied for user 'foo'@'::1' (using password: NO)
if strings.Contains(err.Error(), "Access denied") {
	// Handle the permission-denied error
}
</pre><p>This is not the best way to do it, though. For example, the string value might
vary depending on what language the server uses to send error messages.  It's
much better to compare error numbers to identify what a specific error is.</p>
<p>The mechanism to do this varies between drivers, however, because this isn't
part of <code class="docutils literal notranslate"><span class="pre">database/sql</span></code> itself. In the MySQL driver that this tutorial focuses
on, you could write the following code:</p>
<pre class="prettyprint lang-go">
if driverErr, ok := err.(*mysql.MySQLError); ok { // Now the error number is accessible directly
	if driverErr.Number == 1045 {
		// Handle the permission-denied error
	}
}
</pre><p>Again, the <code class="docutils literal notranslate"><span class="pre">MySQLError</span></code> type here is provided by this specific driver, and the
<code class="docutils literal notranslate"><span class="pre">.Number</span></code> field may differ between drivers. The value of the number, however,
is taken from MySQL's error message, and is therefore database specific, not
driver specific.</p>
<p>This code is still ugly. Comparing to 1045, a magic number, is a code smell.
Some drivers (though not the MySQL one, for reasons that are off-topic here)
provide a list of error identifiers. The Postgres <code class="docutils literal notranslate"><span class="pre">pq</span></code> driver does, for example, in
<a class="reference external" href="https://github.com/lib/pq/blob/master/error.go">error.go</a>. And there's an
external package of <a class="reference external" href="https://github.com/VividCortex/mysqlerr">MySQL error numbers maintained by
VividCortex</a>. Using such a list, the
above code is better written thus:</p>
<pre class="prettyprint lang-go">
if driverErr, ok := err.(*mysql.MySQLError); ok {
	if driverErr.Number == mysqlerr.ER_ACCESS_DENIED_ERROR {
		// Handle the permission-denied error
	}
}
</pre></div>
<div class="section" id="handling-connection-errors">
<h1>Handling Connection Errors<a class="headerlink" href="#handling-connection-errors" title="このヘッドラインへのパーマリンク">¶</a></h1>
<p>What if your connection to the database is dropped, killed, or has an error?</p>
<p>You don't need to implement any logic to retry failed statements when this
happens. As part of the <a class="reference external" href="connection-pool.html">connection pooling</a> in
<code class="docutils literal notranslate"><span class="pre">database/sql</span></code>, handling failed connections is built-in. If you execute a query
or other statement and the underlying connection has a failure, Go will reopen a
new connection (or just get another from the connection pool) and retry, up to
10 times.</p>
<p>There can be some unintended consequences, however. Some types of errors may be
retried when other error conditions happen. This might also be driver-specific.
One example that has occurred with the MySQL driver is that using <code class="docutils literal notranslate"><span class="pre">KILL</span></code> to
cancel an undesired statement (such as a long-running query) results in the
statement being retried up to 10 times.</p>
<p><strong>Previous: <a class="reference external" href="prepared.html">Using Prepared Statements</a></strong>
<strong>Next: <a class="reference external" href="nulls.html">Working with NULLs</a></strong></p>
</div>


          </div>
          
        </div>
      </div>
      <div class="sphinxsidebar" role="navigation" aria-label="main navigation">
        <div class="sphinxsidebarwrapper">
  <h3><a href="index.html">目次</a></h3>
  <ul>
<li><a class="reference internal" href="#">layout: article
title: Handling Errors</a></li>
<li><a class="reference internal" href="#errors-from-iterating-resultsets">Errors From Iterating Resultsets</a></li>
<li><a class="reference internal" href="#errors-from-closing-resultsets">Errors From Closing Resultsets</a></li>
<li><a class="reference internal" href="#errors-from-queryrow">Errors From QueryRow()</a></li>
<li><a class="reference internal" href="#identifying-specific-database-errors">Identifying Specific Database Errors</a></li>
<li><a class="reference internal" href="#handling-connection-errors">Handling Connection Errors</a></li>
</ul>
<div class="relations">
<h3>Related Topics</h3>
<ul>
  <li><a href="index.html">Documentation overview</a><ul>
  </ul></li>
</ul>
</div>
  <div role="note" aria-label="source link">
    <h3>このページ</h3>
    <ul class="this-page-menu">
      <li><a href="_sources/errors.md.txt"
            rel="nofollow">ソースコードを表示</a></li>
    </ul>
   </div><div>
    <h4>Page Info</h4>
    <p>
        <ul>
            <li>英数記号: 6190</li>
            <li>非アスキー: 0</li>
            <li>合計文字数: 6190</li>
            <li>半角換算: 6190</li>
            <li>全角換算: 3095.0</li>
        </ul>
    </p>
</div>
<div id="searchbox" style="display: none" role="search">
  <h3 id="searchlabel">クイック検索</h3>
    <div class="searchformwrapper">
    <form class="search" action="search.html" method="get">
      <input type="text" name="q" aria-labelledby="searchlabel" />
      <input type="submit" value="検索" />
    </form>
    </div>
</div>
<script type="text/javascript">$('#searchbox').show(0);</script>
        </div>
      </div>
      <div class="clearer"></div>
    </div>
    <div class="footer">
      &copy;VividCortex (translated by @d-tsuji).
      
      |
      Powered by <a href="http://sphinx-doc.org/">Sphinx 2.3.1</a>
      &amp; <a href="https://github.com/bitprophet/alabaster">Alabaster 0.7.12</a>
      
      |
      <a href="_sources/errors.md.txt"
          rel="nofollow">Page source</a>
    </div>

    

    
  </body>
</html>